Narrative arcs + multiple shared decks (building)
=================================================
:author: Arnauld Van Muysewinkel <arnauldvm@gmail.com>
:revnumber: 0.1
:revdate: 2016-10-20
:revstatus: WiP
:doctype: article
:lang: fr
:encoding: utf8
:toc:
:toc-placement: manual
:toclevels: 4
:toc-title: Contenu
//:numbered:

:delstyle: line-through

ifdef::env-maven[]
// make the document more portable:
:icons: font
endif::env-maven[]

ifdef::env-github[]
:delstyle: .cm-strikethrough
// replacement for icons:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::env-github[]


30-Jun-'13

Nouvelle version
----------------

Carnet de notes
~~~~~~~~~~~~~~~

Matériel
^^^^^^^^

* Cartes : deck de pioche : *monstres* {-}, *pièges*
{-}, *trésors* +++{+}+++, *améliorations*
+++{+}+++ ({-}=dos rouge,
+++{+}+++=dos bleu)
** + 4 cartes *porte* et/ou *escalier* par *donjon* (1 par
niveau) + 1 carte *aventurier* (+1 pion) par joueur
** on garde l'idée des *modules* (càd le deck est constitué de plusieurs
paquets de cartes (un par joueur), chaque module étant thématisé
(morts-vivants, peaux vertes, chaos ...) et comprennant le
nombre de cartes suffisant pour un joueur.
* 4 Niveaux, _n_+1 donjons (si _n_ joueurs), les portes
pourraient être imprimées sur des plateaux de jeu au lieu de cartes

But du jeu
^^^^^^^^^^

Être le premier à amasser une richesse correspondant à X *pièces d'or*

Préparation
^^^^^^^^^^^

* au début : 5 cartes en main par joueur + draft
* on révèle les 3 premières carte de la pioche (= la rivière)

Tour de jeu
^^^^^^^^^^^

À son tour un joueur exécute 2 phases : le dungeon *building*, puis le
dungeon *crawling* (ou l'inverse ?)

*Building* :

* le joueur pose autant de cartes qu'il veut sur les donjons (max 2 par
donjon)
* règles de pose : sur n'importe quel niveau de n'importe quel donjon,
de gauche à droite, face cachée (uniquement la couleur du dos, et donc
le type de carte, est visible), de plus il faut respecter la contrainte
de niveau de la carte (exemple : "2-3" → niveaux 2 à 3
uniquement)
* lorsqu'il a terminé, il tire des cartes pour compléter sa main, chaque
carte est tirée au choix soit de la pioche (cachées), soit de la rivière
(visibles), à chaque fois qu'il choisit une carte visible il la remplace
immédiatement en retournant une carte de la pioche

*Crawling* : 2 possibilités : *repos*, *aventure*

* [underline]#repos#
** _au village_ : le pion doit être présent devant le joueur au début du
tour, l'aventurier ne peut rien faire d'autre pendant le tour, il
récupère tous ses curseur au max (force, vie, pouvoir)
** _dans un donjon_ : le pion doit être présent dans un donjon au début
du tour, l'aventurier ne peut rien faire d'autre pendant le tour,
chaque(?) curseur (vie, force, pouvoir) peut remonter d'1(?) unité à
concurrence de son maximum
* [underline]#aventure au donjon# : le joueur enchaîne des actions parmi les
suivantes (il s'arrête quand il veut) : *entrée* dans un donjon,
*revenir* au village, *avancer* sur la carte suivante, *passer*
** _entrée au donjon_ : le pion doit se trouver au village, choisir un
donjon et poser le pion sur la porte du 1er niveau, [underline]#il faut qu'il y
ait au moins une carte dans le 1er niveau de ce donjon#
** _revenir au village_ : placer le pion au village, le joueur ne peut
plus que passer (il devra attendre le tour suivant s'il veut passer)
** _passer_ : fin de la phase de crawling, c'est au tour du joueur
suivant
** _avancer sur la carte suivante_ : il faut qu'il y ait une carte
"suivante", retourner face visible la première carte (à gauche) du
niveau où se trouve le pion du joueur, placer le pion sur cette carte,
résoudre immédiatement la rencontre décrite par la carte
*** lorsqu'il n'y a pas de carte suivante sur le niveau actuel du
donjon, on peut passer au niveau suivant immédiatement, pour autant
qu'il y ait au moins une carte sur ce niveau, sinon fin de donjon et
retour automatique au village
*** on pourrait imposer l'utilisation d'un escalier pour passer au
niveau suivant, auquel cas les escaliers se poseraient face visible
(sauf escaliers cachés ?) et clôtureraient (ou pas?) un niveau
&rarr; à voir pendant les tests

? Ajouter un 'marché' pour améliorer l'aventurier hors donjon ?
&rarr; uniquement si ça peut résoudre des problèmes d'équilibrage.

Résolution des rencontres
^^^^^^^^^^^^^^^^^^^^^^^^^

* trésor : placer la carte dans les possessions de l'aventurier (à côté
de la carte aventurier), si la carte représente des pièces, remplacer
par des jetons pièces d'or et mettre la carte dans la défausse
* amélioration : placer la carte dans les possessions de l'aventurier,
les nouvelles valeurs de compétences sont directement applicables
** l'effet d'une amélioration peut être à usage *unique*, *permanent*,
ou *immédiat*, on remet la carte dans la défausse après utilisation
(sauf si permanent)
* monstre/piège :
** la première ligne indique la/les *condition(s)* à remplir par
l'aventurier pour remporter le combat
** la deuxième ligne indique la/les *conséquence(s)* pour l'aventurier
en cas de *victoire*
** la troisième ligne indique la/les *conséquence(s)* pour l'aventurier
en cas de *défaite*
:: Exemple :
::: [underline]#Condition#: Force >=4 | Pouvoir >=2
::: [underline]#Victoire#: Vie -2 & Or +1
::: [underline]#Défaite#: Vie -3
::: (Les conditions et conséquences peuvent utiliser des opérateurs
logiques (&, |))
** mort de l'aventurier : lorsque les points de vie arrivent à 0 (ou
moins), le pion revient au village, une carte de l'équipement tirée au
hasard est défaussée, (et il faudra encore passer un tour pour récupérer
tous les points de vie) (respawn)
** en cas de victoire, la carte de monstre est défaussée, à moins
qu'elle ne figure un trésor, auquel cas elle est traitée comme une carte
trésor
** en cas de défaite, le joueur passe, son pion reste bloqué sur la
carte et il ne pourra pas continuer sa progression tant que cette carte
n'est pas battue

Composition d'un module
^^^^^^^^^^^^^^^^^^^^^^^

50 cartes :

* 2 aventuriers (1 carte devra être écartée)
* 8 escaliers(?)
* 12 monstres répartis entre les niveaux 1 à 4, par exemple : 4L1, 4L2,
2L3, 2L4
* 6 pièges
* 8 trésors
* 8 améliorations
* 6 événements spéciaux

&rarr; https://docs.google.com/spreadsheets/d/1OQAYdWOY2dhdnjVGGqx_NlSOnSvBfDpd-nKg32b-MZ0/edit?usp=sharing[liste des cartes par module]

Ancienne version
----------------

Le jeu
~~~~~~

Les joueurs incarnent des aventuriers qui partent explorer des donjons
pour récolter des richesses.

* donjons = des lignes de cartes constituées en commun par les joueurs
* aventurier = la main de cartes de chaque joueur
* le recto de chaque carte est divisé en deux parties :
** côté "donjon" : un monstres, ou piège, ou trésor, ou autre rencontre
** côté "aventurier" : 1 équipement, ou caractéristique spéciale, ou
sort ... ; ou _re-fill_ d'une jauge (x PV, x mana ...)

****
_Ou pas. Si on met un peu plus d'items dans les donjons, le
personnage peut évoluer par l'exploration des donjons __uniquement__. Cela
simplifie et permet de recentrer le jeu sur les donjons. Dans ce cas pas
besoin de côté "aventurier". Par contre une même carte devrait pouvoir
combiner plusieurs choses (monstre et trésor, piège et trésor ...)_ (Le
verso est uniforme et identique pour toutes les cartes.)
****

Phases
~~~~~~

Les donjons doivent recéler des surprises, mais il faut limiter le
hasard &rArr; une partie des cartes posées sur les donjons sont cachées
(soit : 1 sur 2 ; soit : en fonction d'une indication sur la carte). À
son tour un joueur pioche une carte et la prend dans sa main. Il choisit
ensuite de poser 0 à n cartes sur un (des?) donjon(s). (_Éviter qu'un
joueur pose tout un donjon en une seule fois &rArr; max 1/2/3 cartes par
donjon à la fois ?_) Tant qu'une carte est en main, c'est le côté
aventurier qui s'applique. Cela peut potentiellement même être un malus
(incitation à poser vite les cartes donjons intéressantes). _(Les
joueurs auront-ils tendance à garder les bonnes cartes et poser
les mauvaises, pour créer des donjons peu intéressants pour les autres;
ou à faire l'inverse, pour s'en créer des intéressants pour soi.
Peut-être cela peut-il s'auto-équilibrer ?)_
Limiter la taille de la main pourrait suffire. Les donjons
ont-ils aussi une taille maximale ? Les donjons pourraient se
construire sur un plan quadrillé, se qui les amèneraient à se rejoindre.

_Autre idée pour le __dungeon building__ : chaque carte correspond à un
(plusieurs) niveaux de profondeur (exple : 2/3/4). La contrainte de pose
est que la profondeur ne peut pas diminuer.
(Exple : 1 - 1 - 1/2 - 3 - 3 - 3 - 6 - 6/7, mais pas 1, 1, 1/2, 2, 1 ...)
Ainsi on garde une croissance en
difficulté du donjon. On évite que le boss de fin apparaisse avant le
gobelin apéritif._

****
_Révision de l'idée : pour chaque donjon, il y a n emplacements
"verticaux" (par exemple 6), correspondant aux niveaux des cartes. Les
cartes sont posées dans l'emplacement correspondant à leur niveau.
Thématiquement, chacun de ces emplacements est une salle (un étage) du
donjon. Certaines cartes peuvent éventuellement avoir plusieurs niveaux
possibles. On peut empiler "horizontalement" plusieurs cartes dans un
emplacement, plusieurs monstres/trésors pouvant être présent dans une
même salle (étage) du donjon. Les cartes d'un même niveau seront
activées dans l'ordre __http://fr.wikipedia.org/wiki/LIFO[LIFO]__.
L'alternance visible/caché se fait verticalement __et__ horizontalement._

Un donjon n'est pas ouvert à l'exploration tant qu'il n'y a pas une
suite ininterrompues de cartes depuis le premier niveau
(pas de "trous") - voire même jusqu'au dernier niveau.
****

Lorsqu'il se sent prêt, un joueur peut lancer son aventurier dans
l'exploration d'un des donjons disponibles. La résolution se fait dans
l'ordre de pose des cartes donjons. Les effets des cartes sont
immédiatement appliqués, avant de retourner la suivante. Un objet trouvé
rejoint la main et pourra être utilisé dès la prochaine rencontre, un
monstre déclenche immédiatement un combat ... Cette phase s'arrête soit
avec l'épuisement des cartes donjon, soit avec la fuite ou la mort de
l'aventurier (impact ?).

****
_Impact de la fuite d'un aventurier : il devra reprendre
l'exploration du donjon depuis le premier niveau, mais comme les
premières cartes auront été éliminées, il devra attendre pour cela que
ces premiers niveaux soient à nouveau remplis._
****

Il sera probablement nécessaire de prévoir que le joueur puisse poser
des cartes devant lui. Permet d'avoir plus de cartes, mais visibles et
pas dispo pour _dungeon building_. _(Ne serait-il pas préférable
que l'exploration du donjon se fasse en phase avec les tours de jeu
(plutôt que dans une phase spéciale ? &rArr; Pas d'attente des autres
joueurs, plus d'interaction, possibilité pour les autres joueurs
d'intervenir sur le deck du donjon en cours d'exploration ... Un joueur,
qu'il soit l'explorateur ou l'un de ses exposants, peut ajouter une
carte dans une salle du donjon en cours d'exploration, à condition que
le personnage ne soit pas encore entré dans cette salle.)_

Les cartes
~~~~~~~~~~

* <<_étude_initiale,Étude_initiale>>
* <<_nouvelle_analyse,Nouvelle_analyse>>

https://docs.google.com/spreadsheet/ccc?key=0Av0yUaMsCLd0dGRNMUZMdmFZMVpBMDNNem5LOGZQVGc&usp=sharing[Liste des cartes sur Google Drive]

Étude initiale
^^^^^^^^^^^^^^

Soit une taille de donjon moyenne de 8 (3 monstres, 1 item, 1 boss, 1
trésor, 1 rencontre autre, 1 "porte"). Soit une taille de set
d'aventurier moyenne de 6 (1 aventurier, 2 compétences, 2 item, 1 don)
(sur table ou en main). Soit 5 dépenses de jauge dépensée par donjon
(PV, sorts ...) Si on veut que chaque joueur ait l'occasion d'explorer 3
donjons en moyenne : n x 3 x (8+5) + n x (6 - 2
[les items sont déjà comptés]) = n x 43 : 43 cartes par aventurier. Un
deck permettant de jouer à 4 devrait donc être constitué de 172 cartes
environ. Il contiendrait : 60 "points de jauge", 48 monstres (36 normaux
+12 boss), 12 items, 12 trésors, 12 rencontres autres, 8
compétences, 4 dons, 12 "portes", 4 aventuriers. _(Revoir la proportion
donjons/aventuriers ?)_ _(Moins de monstres plus d'items ?)_
_(Aventuriers identiques ou différents (si différents, prévoir plus que
4 pour choix) ?)_

Un personnage (aventurier ou monstre) a les caractéristiques suivantes :

* attaque
* défense
* vie
* constitution
* esprit (optionnel)

Les autres cartes agissent sur ces caractéristiques (bonus, malus ...).
Elles agissent, soit de manière permanente, soit un nombre de fois
limité n (<=4).

****
_Les cartes qui agissent un nombre de fois limité portent les
numéros de n à 1 sur les côtés. Chaque fois qu'elle est utilisée, on
fait faire un quart de tour à la carte de manière à ce que soit visible
le nombre d'utilisations restantes._
****

La résolution du combat est déterministe. Un round de combat se résout
en simultané pour les 2 protagonistes. Chacun perd en points de vie la
différence entre l'attaque de l'adversaire et sa propre défense. Si sa
défense est supérieure à l'attaque de l'adversaire il ne perd rien. On
répète les rounds immédiatement jusqu'à ce que les points de vie d'un
des adversaires tombe à 0 ou moins.


****
[underline]#!!!!!!!!#

[underline]#Ce système n'est pas tenable. Une estimation rapide donne qu'il
faudrait en moyenne 3 tours pour éliminer un monstre. À supposer que
chaque joueur explore +++~+++3 donjons par partie, contenant
+++~+++3 monstres, cela ferait au minimum 27 tours par joueur, sans
compter les tours passés à se reposer, les combats perdus ... Soit
vraisemblablement 40 tours de jeu par partie. En comptant 1'30" de
réflexion par joueur, on arrive à 120 min par partie !#

[underline]#C'est beaucoup trop long.# [underline]#D'autant plus que tous les tours
passés à combattre un monstre sont autant de tours où l'adversaire peut
continuer à renforcer les défenses du donjon en cours d'exploration.
Cela risque de rendre les explorations interminables.#

[underline]#Si on arrive à résoudre un combat en 1 tour, on arrive à 9 tours
pour éliminer les monstres, soit max 20 tours au total ce qui ramènerait
la durée à 60 min.#

[underline]#C'est bien plus raisonnable.#

[underline]#Cela semble tout à fait faisable, puisque les combats sont tout à
fait déterministes. Cela les rendra d'ailleurs moins ennuyants.#


****


À l'issue de chaque round l'aventurier peut rompre le combat en fuyant.
Dans ce cas, il quitte immédiatement le donjon et revient devant son
propriétaire. Le monstre remet toutes ses jauges au maximum.

****
Optionnel: Il perd (et laisse sur place) 1 objet au hasard
****

Une fois revenu devant le joueur, l'aventurier est au repos. Il regagne
1 PV par tour, [underline]#ou# 1 point d'esprit en échange de 3(?) PV. (Sans
jamais dépasser le max des jauges.)

Une fois un monstre battu, on gagne sa carte (si elle comporte un/des
items), ou on la défausse. La carte suivante ne pourra être résolue
qu'au tour suivant. On ne pénètre dans une nouvelle salle qu'au moment
où on commence à résoudre ses cartes.

Une carte item se résout en la prenant immédiatement. Si la carte
augmente le maximum de points de vie de n, le personnage augmente
instantanément son total actuel de points de vie de n.

Une carte piège se résout en appliquant les effets indiqués.

Au début de chaque round, le joueur peut décider de déclencher l'effet
d'une (_ou plusieurs ? combien max ?_) carte item.

****
&#9986; [{delstyle}]#Optionnel: Certaines cartes effets (sorts) ont des conditions
d'utilisation liées à la caractéristique d'esprit.# +
La dépense d'un point d'esprit permet de s'immuniser des effets d'un
pouvoir spécial.
****

Entre chaque tour, un aventurier gagne un nombre de points de vie égal à
sa constitution (sans jamais dépasser le maximum).

Nouvelle analyse
^^^^^^^^^^^^^^^^

Jauges
++++++

(Inspiration : Mice & Mystics (M&M), Zombie 15' (Z15) ...)

* La plupart des monstres n'ont qu'1 PV &rArr; pas besoin de faire le
décompte des PV, il suffit de retirer la carte quand elle est détruite
* Quelques gros monstres peuvent avoir quelques PV
* Les aventuriers ont quelques PV (genre 3-4).
* On tient le compte en déposant des jetons blessure. Lorsque le perso
est soigné, il suffit de retirer toutes les blessures. les blessures
peuvent être de différents types (normale, poison, magique ...) selon
couleur (rouge, vert, bleu ...)

De plus ça permet d'éliminer les monstres (sauf les plus gros) plus
rapidement (1-2 tours), ce qui répond à une des critiques
ci-dessus.

Dés
+++

Autre idée : Le système actuel rend les combats prédéterminés, ce qui
risque de rendre le jeu trop calculatoire et peu dynamique. De plus on
risque d'avoir vite des situations de blocage par manque de granularité
&rArr; très complexe à équilibrer. Donc, je me propose de rendre le système
plus aléatoire par l'introduction de dés.

Utiliser des dés standard rendrait le jeu moins fluide (E.g. : j'ai une
épée qui touche sur un 3, mais l'adversaire à un bouclier ... et j'ai un
bonus de force ... :-/).

On pourrait utiliser des dés style FFG/M&M : les face présentent des
symboles qui déterminent les actions réussies (&rArr; granularité des taux
de réussite = 17%). J'imagine même qu'on fonction du type de créature /
arme / ..., on utilise un dé différent, avec une répartition différente
des symboles.

Symboles::

* épées = attaque (combat) réussie
* étoile = attaque magique réussie
* bouclier = défense
* etc.

Cartes
++++++

L'ensemble des cartes actuel est trop vaste et manque de consistance. Je
me propose de réduire ce problème en considérant que le jeu est
constitué de plusieurs modules, chaque module ayant une unité thématique
(e.g. goblinoïdes, draconiques, morts-vivants, chaotiques ...).
Cela permet également d'ajuster facilement la taille du jeu au nombre de
joueurs (un module par joueur) tout en garantissant la bonne répartition
des cartes. Et, last but not least, cela permet d'envisager très
facilement des extensions.

La taille d'un module reste à affiner. Sur base des chiffres plus haut,
il faut (172-4x3x5=) 112 cartes pour 4 joueurs (on n'a plus
besoins de cartes de jauge si on utilise des jetons). Cela ferait
112/4=28 cartes, cela rejoint mon idée intuitive d'une taille de l'ordre
de 32 ...

De quoi serait constitué un module ? Sur base de la répartition calculée
plus haut :

* 9 monstres, 3 boss; soit 12
* 1 aventurier
* 3 portes
* 3 rencontres
* 3 objets, 3 trésors; soit 6
* 2 compétences, 1 don; soit 3

En reconsidérant :

* 14 monstres : 4L1, 4L2, 2L3, 2L4, 1L5, 1L6
* 1 aventurier
* 3 portes
* 3 rencontres
* 3 objets, 5 trésors; soit 8
* 3 compétences/dons

Soit 32 cartes.

Autres aspects à développer
~~~~~~~~~~~~~~~~~~~~~~~~~~~

Tutoriel ::
Le deck de carte est vendu trié suivant un ordre prédéfini, avec
des cartes d'explication intégrées. Le joueur joue sa première aventure
solo tout en découvrant l'essentiel des règles au fur et à mesure (cf.
http://www.boardgamegeek.com/boardgame/127398/legends-of-andor[Andor]).

Règles de campagne ? ::

Règles solo ! ::

Chaque porte activant des règles particulières ::

Autre option de développement ::
les joueurs ne contrôlent pas 1 aventurier en particulier, mais
incarnent des puissances divines qui manipulent l'ensemble des
aventuriers pour renforcer leur influence sur le monde (...?)

Recherche autour du nom
~~~~~~~~~~~~~~~~~~~~~~~

Le nom que j'utilise actuellement "Narrative Arcs Building" (NAB) n'est
pas très sexy et n'a plus grand-chose à voir avec ce qui se
passe dans le jeu.

Il faudrait donc trouver un nom plus sexy pour le proto.

Recherche terminologique (fr vs. en) ::
donjon - keep +
cachot - dungeon, oubliette +
oubliette - oubliette +
souterrain - tunnel, underground +
crypte, caveau - crypt, vault +
caverne - cave, cavern +
galerie - tunnel, gallery, (drift) +
grotte - cave +
antre - lair, den, haunt +
gouffre - chasm, abyss, gulf +
catacombes - catacombs +
repaire - den, lair +
paquet - deck +
carte - card +
monstre - monster +
&nbsp; - explorer, adventurer, traveler, pathfinder, pioneer,
wanderer, venturer, venture

Idées retenues ::
*Underground Ventures*
